

## Generate turn numbers and other vars
turn_df <- data.frame(
  cons_date = rep(1:200, each = 4),
  turn_num = seq(0, 799)
)

# cons_date <- rep(1:200, each = 4)
# turn_num <- seq(0, 800)

season_change_turn <- seq(2, 800, by = 4)


fileName <- sprintf("4tpy_AV.txt")

message(sprintf("Writing %s...", fileName))
r <- file(fileName, open = "w")

cat(file = r, "; GENERATED by RN-7 via R script\n\n")

cat(file = r, "script\n\n")

cat(file = r,
    "; 4 turns per year script\n")

cat(file = r,
    "; starting year: 1, ending year: 200\n\n")

cat(file = r,
    "while I_TurnNumber < 800\n\n")

cat(file = r,
    "suspend_during_battle on")

## for loop
for (i in 1:nrow(turn_df)) { # 1:nrow(turn_df)
  # print(turn_df[i, 1]) # cons_date
  # print(turn_df[i, 2]) # turn_num

  ## check if 'i' is season changing turn
  if (turn_df[i, 2] %in% season_change_turn) {
    cat(file = r,
        sprintf("
    console_command date %s
    console_command season summer
    monitor_event FactionTurnEnd FactionType slave
        if I_TurnNumber = %s
                console_command season summer
        end_if
    terminate_monitor
    end_monitor
    while I_TurnNumber = %s
    end_while\n\n",
    turn_df[i, 1], turn_df[i, 2], turn_df[i, 2]
        )
    )
  } else {
    cat(file = r,
        sprintf("
    console_command date %s
    console_command season summer
    while I_TurnNumber = %s
    end_while\n\n",
    turn_df[i, 1], turn_df[i, 2]
        )
    )
  }
}

## Close ----
close(r)















cat(file = r,
    sprintf("
    console_command date 1
    console_command season summer
    while I_TurnNumber = 0
    end_while

    console_command date 1
    console_command season summer
    while I_TurnNumber = 1
    end_while

    console_command date 1
    console_command season summer
    monitor_event FactionTurnEnd FactionType slave
        if I_TurnNumber = 2
                console_command season summer
        end_if
    terminate_monitor
    end_monitor
    while I_TurnNumber = 2
    end_while

    console_command date 1
    console_command season summer
    while I_TurnNumber = 3
    end_while",
    cons_date[[1]], cons_date[[2]], cons_date[[3]], cons_date[[4]]
    )
)




for (i in 1:length(fieldcl)) {
  cat(file = r, sprintf("expect_type(team_output$%s, '%s')\n",
                        names(fieldcl)[i], fieldcl[i]))
}

## Close ----
close(r)
